import numpy as np
import matplotlib.pyplot as plt

"""
stitches images generated by matplotlib from numpy arrays into a video
"""


def stitch_images_to_video():
	return None


def generate_scatter_plots():
	pass


if __name__ == "__main__":
	generate_scatter_plots()
	stitch_images_to_video()
